export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";

export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAIL = "FETCH_PRODUCT_FAIL";

export const FETCH_RELATED_PRODUCTS_REQUEST = "FETCH_RELATED_PRODUCTS_REQUEST";
export const FETCH_RELATED_PRODUCTS_SUCCESS = "FETCH_RELATED_PRODUCTS_SUCCESS";
export const FETCH_RELATED_PRODUCTS_FAIL = "FETCH_RELATED_PRODUCTS_FAIL";
